name: frontend-check-codebase

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-check-codebase.yaml'

jobs:
  check-codebase:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: frontend

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.node-version
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Run Format and Lint Check
        run: pnpm run check
