name: frontend-build-and-deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: frontend/package.json
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: frontend/.node-version
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm pages:build

      - name: Publish to Cloudflare Pages
        id: cloudflare-pages-deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: frontend
          command: pages deploy

      # - name: Add publish URL as commit status
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const sha = context.payload.pull_request?.head.sha ?? context.sha;
      #       await github.rest.repos.createCommitStatus({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         context: 'Cloudflare Pages',
      #         description: 'Cloudflare Pages deployment',
      #         state: 'success',
      #         sha,
      #         target_url: "${{ steps.cloudflare-pages-deploy.outputs.deployment-url }}",
      #       });
